// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePlugin = "plugin"

// Plugin mapped from table <plugin>
type Plugin struct {
	ID                    string `gorm:"column:id;primaryKey" json:"id"`
	SoftwareSourceCodeID  string `gorm:"column:software_source_code_id;not null" json:"software_source_code_id"`
	SoftwareApplicationID string `gorm:"column:software_application_id;not null" json:"software_application_id"`
	Version               string `gorm:"column:version;not null" json:"version"`
	ProxyType             string `gorm:"column:proxy_type;not null" json:"proxy_type"`
	Runtime               string `gorm:"column:runtime;not null" json:"runtime"`
	Execution             string `gorm:"column:execution;not null" json:"execution"`
	Installed             bool   `gorm:"column:installed;not null" json:"installed"`
	Enabled               bool   `gorm:"column:enabled;not null" json:"enabled"`
}

// TableName Plugin's table name
func (*Plugin) TableName() string {
	return TableNamePlugin
}
