// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePluginRelation = "plugin_relations"

// PluginRelation mapped from table <plugin_relations>
type PluginRelation struct {
	ID           string `gorm:"column:id;primaryKey" json:"id"`
	PluginID     string `gorm:"column:plugin_id;not null" json:"plugin_id"`
	RelationID   string `gorm:"column:relation_id;not null" json:"relation_id"`
	RelationType string `gorm:"column:relation_type;not null" json:"relation_type"`
	InputFormat  string `gorm:"column:input_format;not null" json:"input_format"`
	OutputFormat string `gorm:"column:output_format;not null" json:"output_format"`
}

// TableName PluginRelation's table name
func (*PluginRelation) TableName() string {
	return TableNamePluginRelation
}
