basePath: /api/converter-service/v1
definitions:
  orms.Plugin:
    properties:
      enabled:
        type: boolean
      execution:
        type: string
      id:
        type: string
      installed:
        type: boolean
      proxy_type:
        type: string
      runtime:
        type: string
      software_application_id:
        type: string
      software_source_code_id:
        type: string
      version:
        type: string
    type: object
  orms.PluginRelations:
    properties:
      id:
        type: string
      plugin_id:
        type: string
      relation_id:
        type: string
      relation_type:
        type: string
    type: object
  routes.HTTPError:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: status bad request
        type: string
    type: object
info:
  contact: {}
  title: Converter Service API
  version: "1.0"
paths:
  /health:
    get:
      description: Check the health of the RabbitMQ connection and the database connection
      produces:
      - application/json
      responses:
        "200":
          description: Healthy
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/routes.HTTPError'
      summary: Check the health of the service
      tags:
      - health
  /plugin-relations:
    get:
      description: Retrieve all plugin relations from the database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/orms.PluginRelations'
            type: array
        "204":
          description: No Content
          schema:
            $ref: '#/definitions/routes.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/routes.HTTPError'
      summary: Get all plugin relations
      tags:
      - plugin-relations
  /plugin-relations/{id}:
    get:
      description: Retrieve a plugin relation from the database
      parameters:
      - description: Plugin Relation ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/orms.PluginRelations'
        "204":
          description: No Content
          schema:
            $ref: '#/definitions/routes.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/routes.HTTPError'
      summary: Get a plugin relation
      tags:
      - plugin-relations
  /plugins:
    get:
      description: Retrieve all plugins from the database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/orms.Plugin'
            type: array
        "204":
          description: No Content
          schema:
            $ref: '#/definitions/routes.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/routes.HTTPError'
      summary: Get all plugins
      tags:
      - plugins
  /plugins/{id}:
    get:
      description: Retrieve a plugin from the database
      parameters:
      - description: Plugin ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/orms.Plugin'
        "204":
          description: No Content
          schema:
            $ref: '#/definitions/routes.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/routes.HTTPError'
      summary: Get a plugin
      tags:
      - plugins
  /plugins/{id}/disable:
    post:
      description: Disable a plugin by its ID
      parameters:
      - description: Plugin ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Plugin {id} disabled correctly
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/routes.HTTPError'
      summary: Disable a plugin
      tags:
      - plugins
  /plugins/{id}/enable:
    post:
      description: Enable a plugin by its ID
      parameters:
      - description: Plugin ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Plugin {id} enabled correctly
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/routes.HTTPError'
      summary: Enable a plugin
      tags:
      - plugins
swagger: "2.0"
