name: release and push to central
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
      - name: Install dependencies
        run: |
          go get -d -v ./...
          go install -v ./...
          CGO_ENABLED=0 GOOS=linux go build
      - name: Docker build
        run: |
          docker build . -t epos/converter-service-go:${{github.ref_name}}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker push
        run: |
          docker push epos/converter-service-go:${{github.ref_name}}